version: "3.8"
services:
  neuropack-node:
    image: sunnyside1/neuropack:latest
    container_name: neuropack-node
    runtime: nvidia
    networks:
      br0:
        ipv4_address: 192.168.1.230
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /mnt/user/appdata/NeuroPack/config:/app/NeuroPack/config
      - /mnt/user/appdata/NeuroPack/data:/app/NeuroPack/data
      - /mnt/user/appdata/ubuntu/ssh:/etc/ssh/keys
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0,1
      - NODE_ID=master-node
      - NODE_PORT=8765
      - WEB_PORT=8080
      - NODE_ROLE=master
    ports:
      - "22:22"
      - "8765:8765"
      - "8080:8080"
    stdin_open: true
    tty: true

networks:
  br0:
    external: true